### ISSUE TITLE
sqlite_triggered_source.xml file_save should be file_open

### ISSUE THREAD

**Issue by potto216** [mhostetter/gr-sqlite#3]
When I use the triggered source component and selected a database to playback, the component said the database would be be overwritten. I changed file_save to file_open and then the message went away.  As a side note where can you find GNURadio documentation on the types file_save and file_open? The closest I could find is https://wiki.gnuradio.org/index.php/GNURadioCompanion which wasn't very detailed.

**Comment by mhostetter** [comment]
Good catch. If you'd like to submit a PR, I'll happily merge it. Otherwise, I can make the change.

As for GNU Radio documentation, agreed. Some places can be spotty. I've honestly found searching github for keywords and code snippets to be successful. Also looking through other known-good out-of-tree modules can turn up hidden features. I believe that's how I discovered the `<type>file_save</type>` tag.

**Comment by potto216** [comment]
Sounds good, I'll submit a PR
